Adds Some More Images to !Mentor and !Yoggers
yogstation13/yogbot pull request #252
Opened 2021-03-31 05:10 UTC by UselessTheremin

froggy left, and nobody else seemed like they were gonna do it. so here we go. there are a few lingering images to coder that i didnt add and may at a later date but im tired rn

i sure hope im doing this right

....
am i?

2021-04-01 18:06 UTC, AshCorr commented
Good stuff

2021-04-01 18:06 UTC, AshCorr requested changes

2021-04-01 18:06 UTC, AshCorr commented on models/Discord/Commands/DiscordCommandMentor.js
> +	    	"https://media.discordapp.net/attachments/734475284446707753/826626004704559154/image0.png"
Missing commas after each line, this is whats causing the build to fail.

2021-04-01 18:06 UTC, AshCorr commented on models/Discord/Commands/DiscordCommandYoggers.js
> +	"https://media.discordapp.net/attachments/734475284446707753/825033507868639262/image0.png"
same as above

2021-04-02 13:49 UTC, UselessTheremin commented
@AshCorr fixed

2021-04-30 18:43 UTC, merged