Adds a mentor ban command
yogstation13/yogbot pull request #263
Opened 2021-07-03 21:57 UTC by LoliconSlayer

# DO NOT MERGE
Self explanatory, needs a role ID for a mentorban role that restricts access to #mentor-public otherwise should be ready to go

2021-07-03 21:58 UTC, N3D6 commented
Thank you. So much. Speedmerge!!!

2021-07-03 22:06 UTC, Cartlord commented
holy shit it's actually happening

2021-07-03 22:16 UTC, adamsong reviewed
Code looks good, just needs the role id

2021-07-13 14:47 UTC, adamsong commented
Is a role going to be added?

2021-07-15 01:58 UTC, TheGamerdk requested changes

2021-07-15 01:58 UTC, TheGamerdk commented on data/discord.json
> +      "inherits": false,
Make it inherit from mentor

2021-07-15 01:58 UTC, LoliconSlayer commented on data/discord.json
> +      "inherits": false,
No.

2021-07-15 01:59 UTC, TheGamerdk commented on data/discord.json
> +      "inherits": false,
Yes.

2021-07-15 02:02 UTC, TheGamerdk requested changes

2021-07-15 02:02 UTC, TheGamerdk commented on data/discord.json
> +      "inherits": false,
```suggestion
      "inherits": “mentor”,
```

2021-07-15 02:02 UTC, LoliconSlayer commented on data/discord.json
> +      "inherits": false,
No.

2021-07-15 02:03 UTC, TheGamerdk commented on data/discord.json
> +      "inherits": false,
```suggestion
      "inherits": “mentor”,
```

2021-07-15 02:03 UTC, LoliconSlayer commented on data/discord.json
> +      "inherits": false,
No.

2021-07-15 02:05 UTC, TheGamerdk commented on data/discord.json
> +      "inherits": false,
```suggestion
      "inherits": ”mentor”,
```

2021-07-15 11:21 UTC, adamsong approved these changes
Does the needful

2021-07-15 11:21 UTC, merged