Rewrites most of the commands and gives them better names
yogstation13/yogbot pull request #275
Opened 2021-08-02 23:22 UTC by redmoogle

This. was. straight. pain.

The commands have been given more friendly names along with their constructors being modified

to use a _probably_ better system thats not using positional arguments.

2021-08-02 23:29 UTC, ToasterBiome requested changes

2021-08-02 23:29 UTC, ToasterBiome commented on config/discord.json
> +  "discord_token": "ODE5OTQ4NzkxNzIwOTY4MjEy.YEuC0Q.KHhDS8yZQssW-YNMLUKFrg3d4fU",
Should this be here?

2021-08-02 23:30 UTC, ToasterBiome commented
well ya fixed it before I even got to comment LOL

2021-08-02 23:37 UTC, LoliconSlayer commented
Please update the image commands to reflect the PR's that just got merged today

2021-08-02 23:46 UTC, redmoogle commented
> Please update the image commands to reflect the PR's that just got merged today

I just forked it 2 hours ago

2021-08-03 00:09 UTC, AshCorr commented
> > Please update the image commands to reflect the PR's that just got merged today
> 
> I just forked it 2 hours ago

conflicts gonna conflict.

2021-08-09 22:34 UTC, AshCorr commented
Not really sure how renaming commands to `iSomething` is better, to me it just seems confusing.

2021-08-09 22:35 UTC, redmoogle commented
> Not really sure how renaming commands to `iSomething` is better, to me it just seems confusing.

That was to group image commands together thing about img tho

2021-08-09 22:42 UTC, AshCorr commented
Every other class in the codebase is in the format of `<ParentClassName><ChildClassName>` and every file has a a class with the same name as the file. Files also follow the CamelCase format where the first character of every word is capitalized.

In other languages prefixing a file with `I` usually indicates its an interface and not an implementation.

I think instead of just prefixing image commands with `i` you should try creating some kind of `DiscordCommandImage` class that all image commands can inherit from to share all of the image randomization & embedding logic.

2021-08-09 23:08 UTC, redmoogle commented
> Every other class in the codebase is in the format of `<ParentClassName><ChildClassName>` and every file has a a class with the same name as the file. Files also follow the CamelCase format where the first character of every word is capitalized.
> 
> In other languages prefixing a file with `I` usually indicates its an interface and not an implementation.
> 
> I think instead of just prefixing image commands with `i` you should try creating some kind of `DiscordCommandImage` class that all image commands can inherit from to share all of the image randomization & embedding logic.

yea but what do I calls the files then just like regular commands? because I changed them to be not super long

2021-09-20 05:24 UTC, alexkar598 commented
Closing because:
1) Cornflaked
2) Theres like 3 different refactors in here
3) I don't see the point in half of them
4) Noone seems to want to merge this PR.

Feel free to fix your PR and find someone to review and merge it then get it reopened.

2021-09-20 05:24 UTC, closed without merging